spar-reuse.client {
    sparri-host = "<CHANGEME>"
    sparri-port = 9090
    mvn-home = "C:\\Program Files\\Java\\apache-maven-3.8.1"
}
host-connection-pool.client {
    max-connections = 4
    min-connections = 1
    max-open-requests = 32
    idle-timeout = infinite
}
