spa-reuse {

    webapi {
        bind-host = "0.0.0.0"
        bind-port = 9090

        analysis-queue-connection-name = "webapi-analysis-queue-connection"
        entity-queue-connection-name = "webapi-entity-queue-connection"
    }
}

akka.http.server {
    idle-timeout = infinite
}